version: "3.9"

services:
  database:
    container_name: database
    image: postgres:16-alpine
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: app
    build: .
    restart: always
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://admin:admin@database:5432/app

volumes:
  postgres-data:
