@baseUrl = http://localhost
@port = 8000
@host = {{baseUrl}}:{{port}}
@contentType = application/json

### Check api status
# @name checkApiStatus
GET {{host}}/
Accept: application/json

### Gel all contacts
# @name getAllContacts
GET {{host}}/contacts

### Get category by slug
# @contactId = {{checkApiStatus.response.body.$.status}}
@contactId = d52b5e0c-ed3c-49e1-9137-d9094ef1014c
GET {{host}}/contacts/{{contactId}}

### Post new contact
# @prompt contactName
POST {{host}}/contacts
Content-Type: {{contentType}}

{
    "name": "{{contactName}}",
    "phone": "{{$randomInt 1111111111 9999999999}}",
    "email": "{{contactName}}@test.com"
}